### PR TITLE
Use libcxxwrap-julia directly

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
[Using the compiled libcxxwrap-julia in CxxWrap](https://github.com/JuliaInterop/libcxxwrap-julia#using-the-compiled-libcxxwrap-julia-in-cxxwrap)

**Comment by SylvainCorlay** [comment]
@wolfv I am a bit confused at why `micromamba activate` would not be recognized as we used the `provision-with-micromamba` action. Am I missing something?

**Comment by SylvainCorlay** [comment]
Hey @barche (happy holidays!) I am working on updating the julia bindings stack here, and just released xtensor-julia 0.10.0.

In this PR, I am trying to test with conda's build of libcxxwrap, by
 - linking directly with it in the test of xtensor-julia
 - specifying the proper entry in Overrides toml when installing CxxWrap.

I have two questions:
 - why do I need CxxWrap.jl at all?
 - there seems to be some issue on OSX when doing this. `C++ exception while wrapping module StdLib: Symbol for type CppBasicString was not found`. Do you have any hints about what is going on?

**Comment by SylvainCorlay** [comment]
> Symbol for type CppBasicString was not found

It may be that the override is not properly handled on OS X, and two different libcxxwrap versions are used.

**Comment by SylvainCorlay** [comment]
> > Symbol for type CppBasicString was not found
>
> It may be that the override is not properly handled on OS X, and two different libcxxwrap versions are used.

OK, using a symlink instead of an overrides yields the same result. So there is something about the way libcxxwrap is built on conda-forge for OSX that does not work for CxxWrap.jl.

**Comment by barche** [comment]
Hi Sylvain, happy holidays too :)

- CxxWrap.jl is needed because some of the type mapping code is in Julia. This is no problem when compiling a wrapper, but when you want to use libcxxwrap-julia at runtime you also need the Julia part installed.
- For the error my guess would be a version mismatch too, although the lates release of CxxWrap and libcxxwrap should match...

**Comment by SylvainCorlay** [comment]
Thanks for responding.

Tag 0.8.3 is pointing to [15d30a1d5952ebacc6bb16a297a236b8be63b763](https://github.com/JuliaInterop/libcxxwrap-julia/commit/15d30a1d5952ebacc6bb16a297a236b8be63b763).
libcxxwrap_julia_jll.j is pointing to [37743e11cda7363a17840fe2353ff78a7e964a2c](https://github.com/JuliaInterop/libcxxwrap-julia/commit/37743e11cda7363a17840fe2353ff78a7e964a2c).

Could the mismatch be due to the "bigobj" flag that was added between the two?

**Comment by barche** [comment]
It's not clear to me which `libcxxwrap-julia` is found, in the config output nothing is placed, because `JlCxx_INCLUDE_DIRS` is no longer defined, the location can now be obtained using e.g. `get_target_property(JlCxx_location JlCxx::cxxwrap_julia LOCATION)`.

Still, it's probably picking up the right one from conda. I do think the symlink command has the wrong order here: 

```
ln -s $CXXWRAP_PREFIX $CONDA_PREFIX
```

Although using the Overrides.toml should be cleaner, where is that set up?

**Comment by SylvainCorlay** [comment]
Thank you for your reply. I eventually got things to pass with the symlink. Now I have to find the right incantations of `Overrides.toml` to not have to do this.

**Comment by SylvainCorlay** [comment]
Thank you for your reply. I eventually got things to pass with the symlink. Now I have to find the right incantations of `Overrides.toml` to not have to do this.

**Comment by SylvainCorlay** [comment]
Eventually I will try to make a conda package for `CxxWrap.jl` that *depends* on the conda package for `libcxxwrap-julia`. That will be a really good test case for the conda packaging of julia package. Really, the outstanding question is the one asked in https://github.com/JuliaInterop/CxxWrap.jl/issues/309.

**Pull request merged**
